export const items =
  [
    {
      id: 1,
      name: "Banana",
      weight: 4,
      value: 2,
      cat: 'a',
    },
    {
      id: 2,
      name: "Rapadura",
      value: 1,
      weight: 3,
      cat: 'a',
    },
    {
      id: 3,
      name: "Maçã",
      weight: 2,
      value: 2,
      cat: 'a',
    },
    {
      id: 4,
      name: "Pão",
      weight: 1,
      value: 3,
      cat: 'a',
    },
    {
      id: 5,
      name: "Feijão Enlatado",
      weight: 1,
      value: 3,
      cat: 'a',
    },
    {
      id: 6,
      name: "Salsicha Enlatada",
      weight: 1,
      value: 3,
      cat: 'a',
    },
    {
      id: 7,
      name: "Água",
      weight: 2,
      value: 5,
      cat: 'a',
    },
    {
      id: 8,
      name: "Ração Operacional",
      weight: 9,
      value: 5,
      cat: 'a',
    },
    {
      id: 9,
      name: "Curativo",
      weight: 1,
      value: 4,
      cat: 'e',
    },
    {
      id: 10,
      name: "Esparadrapos",
      weight: 3,
      value: 4,
      cat: 'e',
    },
    {
      id: 11,
      name: "Gaze",
      weight: 4,
      value: 3,
      cat: 'e',
    },
    {
      id: 12,
      name: "Kit Sutura",
      weight: 1,
      value: 3,
      cat: 'e',
    },
    {
      id: 13,
      name: "Adrenalina",
      weight: 1,
      value: 2,
      cat: 'e',
    },
    {
      id: 14,
      name: "Morfina",
      weight: 2,
      value: 1,
      cat: 'e',
    },
    {
      id: 15,
      name: "Torniquete",
      weight: 2,
      value: 2,
      cat: 'e',
    },
    {
      id: 16,
      name: "Sabonte",
      weight: 4,
      value: 1,
      cat: 'h',
    },
    {
      id: 17,
      name: "Shampoo",
      weight: 1,
      value: 1,
      cat: 'h',
    },
    {
      id: 18,
      name: "Creme dental",
      weight: 1,
      value: 1,
      cat: 'h',
    },
    {
      id: 19,
      name: "Colírio",
      weight: 2,
      value: 1,
      cat: 'h',
      },
    {
      id: 20,
      name: "Escova de dente",
      weight: 5,
      value: 3,
      cat: 'h',
    }
  ]